export MPFR_VERSION="3.1.5"
export GMP_VERSION="6.1.2"
export MPC_VERSION="1.0.3"
export TEXINFO_VERSION="6.3"

echo "$MPFR_VERSION"
echo "$GMP_VERSION"
echo "$MPC_VERSION"
echo "$TEXINFO_VERSION"


echo "$MPFR_VERSION" >> MPFR_VERSION.com
echo "$GMP_VERSION" >> GMP_VERSION.com
echo "$MPC_VERSION" >> MPC_VERSION.com
echo "$TEXINFO_VERSION" >> TEXINFO_VERSION.com
