//headers for OS

#include "math.h"
#include "string.h"
#include "error.h"
#include "debug.h"
#include "ascii.h"
#include "cpu/cpu.h"
#include "tools/tools.h"
#include "multiboot.h"
#include "vga.h"
#include "mem/memory.h"
#include "pm/pm.h"
#include "console.h"
#include "keyboard.h"
#include "clock.h"
#include "ata.h"
#include "fs/file_system.h"
#include "mem/ramdisk.h"
